//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registration.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cource
    {
        public Cource()
        {
            this.SRegistrations = new HashSet<SRegistration>();
        }
    
        public int CId { get; set; }
        public string CName { get; set; }
        public string Credit { get; set; }
        public int TCapacity { get; set; }
        public int Count { get; set; }
    
        public virtual ICollection<SRegistration> SRegistrations { get; set; }
    }
}
