//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registration.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RegistrationEntities1 : DbContext
    {
        public RegistrationEntities1()
            : base("name=RegistrationEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admins { get; set; }
        public DbSet<Cource> Cources { get; set; }
        public DbSet<Registration> Registrations { get; set; }
        public DbSet<SRegistration> SRegistrations { get; set; }
        public DbSet<Student> Students { get; set; }
    }
}
