//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntroWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.SRegistrations = new HashSet<SRegistration>();
        }
    
        public int SId { get; set; }
        public string SName { get; set; }
        public string SGmail { get; set; }
        public string SPassword { get; set; }
    
        public virtual ICollection<SRegistration> SRegistrations { get; set; }
    }
}
