// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class CartsTblCreated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CartsTblCreated));
        
        string IMigrationMetadata.Id
        {
            get { return "202510101243090_CartsTblCreated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
