//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Thesis.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public int SectionId { get; set; }
        public string Topic { get; set; }
        public string Supervisor { get; set; }
        public int Id { get; set; }
        public string SectionName { get; set; }
    
        public virtual Supervisor Supervisor1 { get; set; }
    }
}
