//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsRegistration.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sport
    {
        public Sport()
        {
            this.Registrations = new HashSet<Registration>();
        }
    
        public int SId { get; set; }
        public string SName { get; set; }
        public int Capacity { get; set; }
        public int Count { get; set; }
    
        public virtual ICollection<Registration> Registrations { get; set; }
    }
}
