//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsRegistration.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Registrations = new HashSet<Registration>();
        }
    
        public int StudentId { get; set; }
        public string StudentName { get; set; }
        public string Gmail { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Registration> Registrations { get; set; }
    }
}
